### ISSUE TITLE
Bots Crashing (Log Enclosed)

### ISSUE THREAD

**Issue by NickDavison** [Steem-FOSSbot/steem-fossbot-voter#119]
018-01-08T07:52:49.176772+00:00 app[api]: Starting process with command `node bot.js` by user scheduler@addons.heroku.com

2018-01-08T07:52:52.514812+00:00 heroku[scheduler.5281]: Starting process with command `node bot.js`

2018-01-08T07:52:53.334246+00:00 heroku[scheduler.5281]: State changed from starting to up

2018-01-08T07:52:55.619464+00:00 app[scheduler.5281]: calling initSteem...

2018-01-08T07:52:55.626990+00:00 app[scheduler.5281]: steem user: #####

2018-01-08T07:52:55.627251+00:00 app[scheduler.5281]: private posting key?: true

2018-01-08T07:52:55.627326+00:00 app[scheduler.5281]: api key?: true

2018-01-08T07:52:55.627399+00:00 app[scheduler.5281]: SendGrid API key?: true

2018-01-08T07:52:55.627469+00:00 app[scheduler.5281]: email address to: none

2018-01-08T07:52:55.627538+00:00 app[scheduler.5281]: email address sender: none

2018-01-08T07:53:27.499445+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=foss-bot-#####.herokuapp.com request_id=c4fd6f05-bd6f-41c1-ada8-ac996c108209 fwd="5.70.7.179" dyno= connect= service= status=503 bytes= protocol=https

2018-01-08T07:53:29.553553+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=foss-bot-#####.herokuapp.com request_id=9f2e39d3-09bc-4ca8-987a-e8946898e349 fwd="5.70.7.179" dyno= connect= service= status=503 bytes= protocol=https

2018-01-08T07:53:35+00:00 app[heroku-redis]: source=REDIS sample#active-connections=2 sample#load-avg-1m=0.175 sample#load-avg-5m=0.22 sample#load-avg-15m=0.255 sample#read-iops=0 sample#write-iops=0 sample#memory-total=15664292kB sample#memory-free=12345056kB sample#memory-cached=1130944kB sample#memory-redis=721040bytes sample#hit-rate=0.99888 sample#evicted-keys=0

**Comment by NickDavison** [comment]
2018-01-08T07:54:46+00:00 app[heroku-redis]: source=REDIS sample#active-connections=2 sample#load-avg-1m=0.1 sample#load-avg-5m=0.185 sample#load-avg-15m=0.235 sample#read-iops=0 sample#write-iops=0 sample#memory-total=15664292kB sample#memory-free=12344380kB sample#memory-cached=1130944kB sample#memory-redis=721040bytes sample#hit-rate=0.99888 sample#evicted-keys=0

2018-01-08T07:55:05.545153+00:00 heroku[scheduler.5281]: Process exited with status 1

2018-01-08T07:55:05.464689+00:00 app[scheduler.5281]: events.js:183

2018-01-08T07:55:05.464700+00:00 app[scheduler.5281]:       throw er; // Unhandled 'error' event

2018-01-08T07:55:05.464703+00:00 app[scheduler.5281]:       ^

2018-01-08T07:55:05.464704+00:00 app[scheduler.5281]: 

2018-01-08T07:55:05.464706+00:00 app[scheduler.5281]: Error: connect ETIMEDOUT 34.225.89.14:443

2018-01-08T07:55:05.464707+00:00 app[scheduler.5281]:     at Object._errnoException (util.js:1024:11)

2018-01-08T07:55:05.464710+00:00 app[scheduler.5281]:     at _exceptionWithHostPort (util.js:1046:20)

2018-01-08T07:55:05.464712+00:00 app[scheduler.5281]:     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)

2018-01-08T07:55:05.560231+00:00 heroku[scheduler.5281]: State changed from up to complete

2018-01-08T07:55:57+00:00 app[heroku-redis]: source=REDIS sample#active-connections=1 sample#load-avg-1m=0.25 sample#load-avg-5m=0.205 sample#load-avg-15m=0.235 sample#read-iops=0 sample#write-iops=0 sample#memory-total=15664292kB sample#memory-free=12341404kB sample#memory-cached=1131336kB sample#memory-redis=700184bytes sample#hit-rate=0.99888 sample#evicted-keys=0

**Comment by bobinson** [comment]
@NickDavison  - did you also get version undefined error as reported in #93 #102 ?

**Comment by thrize** [comment]
Yes it's the same issue, closing as a duplicate but thank you @NickDavison
