### ISSUE TITLE
Edit algo: Import algorithm doesn't work

### ISSUE THREAD

**Issue by thrize** [Steem-FOSSbot/steem-fossbot-voter#124]
Importing the algorithm as JSON text is broken as of #64. It causes the application to crash with the following log:

```
 persistObj save to db algorithm
 /app/node_modules/mongodb/lib/utils.js:98
     process.nextTick(function() { throw err; });
                                   ^
 
 TypeError: callback is not a function
     at /app/lib.js:1730:7
     at handleCallback (/app/node_modules/mongodb/lib/utils.js:96:12)
     at /app/node_modules/mongodb/lib/collection.js:1176:5
     at handleCallback (/app/node_modules/mongodb/lib/utils.js:96:12)
     at /app/node_modules/mongodb/lib/collection.js:659:5
     at /app/node_modules/mongodb-core/lib/topologies/server.js:756:13
     at Callbacks.emit (/app/node_modules/mongodb-core/lib/topologies/server.js:95:3)
     at Connection.messageHandler (/app/node_modules/mongodb-core/lib/topologies/server.js:243:23)
     at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:262:22)
     at emitOne (events.js:116:13)
     at Socket.emit (events.js:211:7)
     at addChunk (_stream_readable.js:263:12)
     at readableAddChunk (_stream_readable.js:250:11)
     at Socket.Readable.push (_stream_readable.js:208:10)
     at TCP.onread (net.js:594:20)
 npm ERR! code ELIFECYCLE
 npm ERR! errno 1
 npm ERR! Voter@0.2.10 start: `node server.js`
 npm ERR! Exit status 1
 npm ERR! 
 npm ERR! Failed at the Voter@0.2.10 start script.
 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
 
 npm ERR! A complete log of this run can be found in:
 npm ERR!     /app/.npm/_logs/2018-01-30T09_08_17_535Z-debug.log
```

**Comment by thrize** [comment]
Fixed in v0.3.0
