### ISSUE TITLE
Steemit updates potentially causing fatal errors

### ISSUE THREAD

**Issue by shaunmza** [Steem-FOSSbot/steem-fossbot-voter#50]
I am seeing errors in my apps logs similar to the following when trying to access my app on heroku.

> 2017-02-17T13:05:49.741203+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=f5.herokuapp.com request_id=e61139e8-9ae8-43dd-97fa-a991e4c4e2bb fwd="" dyno= connect= service= status=503 bytes=

Additionally, when the scheduler runs, it seems to hit an exception when making the api call, as seen by the following log entries;

> 2017-02-17T13:06:02.540589+00:00 app[scheduler.4785]: events.js:160
2017-02-17T13:06:02.540591+00:00 app[scheduler.4785]: throw er; // Unhandled 'error' event
2017-02-17T13:06:02.540591+00:00 app[scheduler.4785]: ^
2017-02-17T13:06:02.540592+00:00 app[scheduler.4785]: 
2017-02-17T13:06:02.540593+00:00 app[scheduler.4785]: Error: unexpected server response (301)
2017-02-17T13:06:02.540593+00:00 app[scheduler.4785]: at ClientRequest.response (/app/node_modules/ws/lib/WebSocket.js:719:15)
2017-02-17T13:06:02.540594+00:00 app[scheduler.4785]: at ClientRequest.g (events.js:291:16)
2017-02-17T13:06:02.540595+00:00 app[scheduler.4785]: at emitOne (events.js:96:13)

This seems to have started happening after recent updates, as per the following link;
[https://steemit.com/tag/@ausbitbank/release-notes-for-steemit-version-0-1-170216](https://steemit.com/tag/@ausbitbank/release-notes-for-steemit-version-0-1-170216)

Thanks :)

**Comment by thrize** [comment]
Thanks for raising this, looking into it immediately as it's a show stopper

**Comment by thrize** [comment]
Issue seems to be with steem.js, I have raised this issue, waiting to see what they turn up

https://github.com/steemit/steem-js/issues/85

**Comment by thrize** [comment]
They have provided a work around implementing this now. Hopefully they will add this to their main files but in the meantime this will fix things.

**Comment by thrize** [comment]
Available in v0.2.1
